- name: add nodejs ppa repo
  apt_repository: repo="ppa:chris-lea/node.js" update_cache=true

- name: install nodejs
  apt: pkg=nodejs state=latest install_recommends=no

- name: install global packages
  npm: name={{item}} global=yes state=latest
  with_items:
    - nodemon
    - bower